### ISSUE TITLE
Please document time bound in README and crate description

### ISSUE THREAD

**Issue by joshtriplett** [mneumann/munkres-rs#1]
Multiple versions of this algorithm exist, some of which run in O(n^4), and some of which run in O(n^3).  Could you please document the time bound for this version in the README and the crate description?

**Comment by MikeCain** [comment]
This repository is a port of [https://github.com/bmc/munkres](https://github.com/bmc/munkres), which labels itself as n^3, so I would think this one should also be n^3.
But an explicit comment somewhere would be nice.

**Comment by mneumann** [comment]
Thanks! Fixed in https://github.com/mneumann/munkres-rs/commit/75f19c85cdbe0f5b0a0cf81d234de45577eaeb86
